=== ZhevahinAndrii/Java-OOP/Laboratory 2/src/resources/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="candies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="candy" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Energy" type="xs:positiveInteger"/>
                            <xs:element name="Type" type="Type" minOccurs="1"/>
                            <xs:element name="Ingredients">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Ingredient" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="IName" type="xs:string"/>
                                                <xs:attribute name="Amount" type="xs:double"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Value">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Proteins" type="xs:double"/>
                                        <xs:element name="Fats" type="xs:double"/>
                                        <xs:element name="CarbonHydrates" type="xs:double"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Production" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="ID" type="xs:unsignedInt" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="Type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Caramel"/>
            <xs:enumeration value="iris"/>
            <xs:enumeration value="chocolate without filling"/>
            <xs:enumeration value="chocolate with filling"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== ZhevahinAndrii/Java-OOP/Laboratory 2/src/resources/xml/data.xml
<?xml version="1.0" encoding="UTF-8" ?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <candy ID="1">
        <Name>Marshmallow Delight</Name>
        <Energy>300</Energy>
        <Type>Caramel</Type>
        <Ingredients>
            <Ingredient IName="Sugar" Amount="20.5"/>
            <Ingredient IName="Fructose" Amount="15.2"/>

        </Ingredients>
        <Value>
            <Proteins>1.2</Proteins>
            <Fats>0.5</Fats>
            <CarbonHydrates>25.0</CarbonHydrates>
        </Value>
        <Production>Roshen fabric</Production>
    </candy>
</candies>
